spring.datasource.url=jdbc:postgresql://ep-fragrant-base-acuhqj3u-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZFsKXY0AHx4h

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true